"""add tender analyses table

Revision ID: 1545737ea415
Revises: 57bad4ff539e
Create Date: 2026-09-09 14:20:19.273760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1545737ea415"
down_revision: str | Sequence[str] | None = "57bad4ff539e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adds `tender_analyses` -- the pliego analysis cache, keyed by the PDF's own content
    hash (not by `expediente`), plus an index on `expediente` for "already analyzed?" lookups.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tender_analyses",
        sa.Column("pdf_hash", sa.String(length=64), nullable=False),
        sa.Column("expediente", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "failed",
                "not_analyzable",
                name="analysisstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["expediente"],
            ["tenders.expediente"],
        ),
        sa.PrimaryKeyConstraint("pdf_hash"),
    )
    op.create_index(
        "ix_tender_analyses_expediente", "tender_analyses", ["expediente"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops `tender_analyses` and its index -- the pliego analysis cache disappears entirely."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tender_analyses_expediente", table_name="tender_analyses")
    op.drop_table("tender_analyses")
    # ### end Alembic commands ###
