"""add generated tsvector column on tender title

Revision ID: 198bdf87e9a5
Revises: 332a9cf3f9c4
Create Date: 2026-09-07 20:27:08.174854

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "198bdf87e9a5"
down_revision: str | Sequence[str] | None = "332a9cf3f9c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adds `title_tsv`, generated and maintained by Postgres from `title`, plus its GIN index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenders",
        sa.Column(
            "title_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('spanish', title)", persisted=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_tenders_title_tsv_gin", "tenders", ["title_tsv"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops `title_tsv` and its GIN index -- the lexical recovery stage loses its index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenders_title_tsv_gin", table_name="tenders", postgresql_using="gin")
    op.drop_column("tenders", "title_tsv")
    # ### end Alembic commands ###
