"""add locations to providers

Revision ID: 332a9cf3f9c4
Revises: 408a569ec4ff
Create Date: 2026-09-07 18:38:40.945572

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "332a9cf3f9c4"
down_revision: str | Sequence[str] | None = "408a569ec4ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Adds the nullable `locations` column -- `None` means no geographic restriction."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("providers", sa.Column("locations", postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops `locations` -- any per-provider geographic restriction is lost."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("providers", "locations")
    # ### end Alembic commands ###
