"""expand contract_type and add cancelled status

Revision ID: 364d5b8e1271
Revises: f980a8b5bd7a
Create Date: 2026-08-17 13:15:56.745716

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "364d5b8e1271"
down_revision: str | Sequence[str] | None = "f980a8b5bd7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Widens `contract_type` from VARCHAR(8) to fit every `ContractType` value.

    `Enum(native_enum=False)` stores as plain VARCHAR with no CHECK constraint
    (SQLAlchemy 2.0 defaults `create_constraint` to False) -- length is the
    only thing the database enforces, sized to the longest value known when
    the column was last created or altered. The initial migration only knew
    three values (longest: 8 chars); `ContractType` has grown to eleven since,
    the longest now 28 chars, hence this ALTER.

    Despite the revision message, `TenderStatus.CANCELLED` needed no matching
    migration: at 9 characters it already fits inside the 19-character width
    `status` got from the original enum's longest value
    (`open_for_submission`), and with no CHECK constraint to update either,
    there was nothing for `--autogenerate` to detect.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenders",
        "contract_type",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum(
            "services",
            "supplies",
            "works",
            "public_services_management",
            "services_concession",
            "public_works_concession",
            "works_concession",
            "public_private_collaboration",
            "special_administrative",
            "private",
            "patrimonial",
            name="contracttype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Narrows `contract_type` back to VARCHAR(8).

    Destructive if any row already holds one of the eight longer values this
    migration added support for -- truncation or a constraint error, not a
    clean revert.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenders",
        "contract_type",
        existing_type=sa.Enum(
            "services",
            "supplies",
            "works",
            "public_services_management",
            "services_concession",
            "public_works_concession",
            "works_concession",
            "public_private_collaboration",
            "special_administrative",
            "private",
            "patrimonial",
            name="contracttype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
