"""expand contract_type and add cancelled status

Revision ID: 364d5b8e1271
Revises: f980a8b5bd7a
Create Date: 2026-08-17 13:15:56.745716

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "364d5b8e1271"
down_revision: str | Sequence[str] | None = "f980a8b5bd7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenders",
        "contract_type",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.Enum(
            "services",
            "supplies",
            "works",
            "public_services_management",
            "services_concession",
            "public_works_concession",
            "works_concession",
            "public_private_collaboration",
            "special_administrative",
            "private",
            "patrimonial",
            name="contracttype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenders",
        "contract_type",
        existing_type=sa.Enum(
            "services",
            "supplies",
            "works",
            "public_services_management",
            "services_concession",
            "public_works_concession",
            "works_concession",
            "public_private_collaboration",
            "special_administrative",
            "private",
            "patrimonial",
            name="contracttype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
