"""create providers table

Revision ID: 408a569ec4ff
Revises: 9aa4cc89cec9
Create Date: 2026-09-07 17:23:49.446731

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "408a569ec4ff"
down_revision: str | Sequence[str] | None = "9aa4cc89cec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Creates the `providers` table, matching `compass.providers.models.Provider` at this revision.

    See its docstring for why the table always holds exactly one row.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("cpv_codes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("min_budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("max_budget", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("annual_revenue", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("certifications", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops the `providers` table -- and the profile row in it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("providers")
    # ### end Alembic commands ###
