"""add gin index on cpv_codes and index on published_at

Revision ID: 9aa4cc89cec9
Revises: 364d5b8e1271
Create Date: 2026-08-20 14:50:49.278899

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aa4cc89cec9"
down_revision: str | Sequence[str] | None = "364d5b8e1271"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tenders_cpv_codes_gin", "tenders", ["cpv_codes"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_tenders_published_at"), "tenders", ["published_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenders_published_at"), table_name="tenders")
    op.drop_index("ix_tenders_cpv_codes_gin", table_name="tenders", postgresql_using="gin")
    # ### end Alembic commands ###
