"""rekey tender_analyses by expediente

Written by hand, not autogenerated: `--autogenerate` sees a primary key moving from one
column to another as "drop the table's identity and build another", with no idea that the
rows in between have to be deduplicated first. It also can't know that a pre-5.2 database
may hold several rows per expediente (one per distinct PCAP ever analyzed), of which only
the newest is the one the new key can keep.

Revision ID: f8bc9ab44cfb
Revises: 151edd6902db
Create Date: 2026-09-11 17:07:46.004931

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8bc9ab44cfb"
down_revision: str | Sequence[str] | None = "151edd6902db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Moves the primary key from `pdf_hash` to `expediente`.

    Keying by the document made two different tenders sharing a byte-identical PCAP
    collide on one row: the second one's reads (which go by expediente) found nothing and
    reported "never analyzed" forever, and two concurrent analyses of it failed on the
    duplicate key. The extraction cache that key existed for now works through
    `ix_tender_analyses_pdf_hash` instead -- same LLM call saved, no shared identity.
    """
    # Only the newest row per expediente survives, since that's the one the reads were
    # already returning (`ORDER BY created_at DESC LIMIT 1`). ctid is Postgres' physical
    # row identifier -- needed here because the table has no unique column left to
    # distinguish two rows of the same expediente once pdf_hash stops being the key.
    op.execute(
        """
        DELETE FROM tender_analyses a
        USING tender_analyses b
        WHERE a.expediente = b.expediente
          AND (a.created_at, a.ctid) < (b.created_at, b.ctid)
        """
    )

    op.drop_index("ix_tender_analyses_expediente", table_name="tender_analyses")
    op.drop_constraint("tender_analyses_pkey", "tender_analyses", type_="primary")
    op.alter_column("tender_analyses", "pdf_hash", existing_type=sa.String(64), nullable=True)
    op.create_primary_key("tender_analyses_pkey", "tender_analyses", ["expediente"])
    op.create_index("ix_tender_analyses_pdf_hash", "tender_analyses", ["pdf_hash"])


def downgrade() -> None:
    """Moves the primary key back to `pdf_hash`.

    Drops rows with no `pdf_hash` first: those are the ones this schema has no way to
    represent (a PCAP over the download cap is recorded with nothing to hash), and a NULL
    can't be part of a primary key.
    """
    op.execute("DELETE FROM tender_analyses WHERE pdf_hash IS NULL")

    op.drop_index("ix_tender_analyses_pdf_hash", table_name="tender_analyses")
    op.drop_constraint("tender_analyses_pkey", "tender_analyses", type_="primary")
    op.alter_column("tender_analyses", "pdf_hash", existing_type=sa.String(64), nullable=False)
    op.create_primary_key("tender_analyses_pkey", "tender_analyses", ["pdf_hash"])
    op.create_index("ix_tender_analyses_expediente", "tender_analyses", ["expediente"])
