"""create tenders table

Revision ID: f980a8b5bd7a
Revises:
Create Date: 2026-08-12 14:21:16.079551

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f980a8b5bd7a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Creates the `tenders` table, matching `compass.tenders.models.Tender` at this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenders",
        sa.Column("expediente", sa.String(), nullable=False),
        sa.Column("contracting_body", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("cpv_codes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("budget_with_vat", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("budget_without_vat", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column(
            "contract_type",
            sa.Enum("services", "supplies", "works", name="contracttype", native_enum=False),
            nullable=False,
        ),
        sa.Column("procedure_type", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "prior_notice",
                "open_for_submission",
                "pending_award",
                "awarded",
                "resolved",
                name="tenderstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("submission_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("pcap_url", sa.String(), nullable=True),
        sa.Column("ppt_url", sa.String(), nullable=True),
        sa.Column("platform_url", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("expediente"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drops the `tenders` table -- and every row in it."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenders")
    # ### end Alembic commands ###
